In [1]:
import numpy as np
import pandas as pd

In [151]:
df = pd.read_csv("ecommerce_messy.csv")
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,City,State,Product_Category,Product_Name,Quantity,...,Discount_%,Payment_Method,Sales_Channel,Order_Status,Delivery_Date,Gross_Sales,Discount_Amount,Net_Sales,Cost,Profit
0,ORD521129,2025-02-12,CUST15482,Vivaan Sharma,42.0,Bangalore,Karnataka,Electronics,Smart Watch,4,...,10.0,Net Banking,Marketplace,Cancelled,2025-02-18,17592.0,1759.2,15832.8,9794.82,6037.98
1,ORD501246,2025-06-04,CUST10010,Pooja Singh,60.0,Ahmedabad,Gujarat,Fashion,Jeans,3,...,0.0,Debit Card,Website,Delivered,2025-06-10,2664.0,0.0,2664.0,1474.13,1189.87
2,ORD507827,2025-05-07,CUST13534,Aarav Kumar,56.0,Mumbai,Maharashtra,Beauty,Face Wash,3,...,25.0,Wallet,Marketplace,Delivered,2025-05-14,1182.0,295.5,886.5,471.03,415.47
3,ORD501610,2025-12-25,CUST15446,Kabir Reddy,41.0,Bangalore,Karnataka,Grocery,Coffee,1,...,15.0,Wallet,Mobile App,Cancelled,2025-12-31,534.0,80.1,453.9,333.30,120.60
4,ORD504043,2025-02-01,CUST16760,Isha Reddy,18.0,Pune,Maharashtra,Electronics,USB-C Hub,4,...,20.0,Net Banking,Marketplace,Returned,2025-02-05,8128.0,1625.6,6502.4,3459.20,3043.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25295,ORD521575,2025-05-24,CUST12470,Rahul Patel,60.0,Chennai,Tamil Nadu,Home & Kitchen,Bedsheet,3,...,20.0,UPI,Mobile App,Processing,2025-05-30,4245.0,849.0,3396.0,2718.69,677.31
25296,ORD505390,2025-06-03,CUST11490,Rahul Singh,55.0,Pune,Maharashtra,Beauty,Sunscreen,3,...,0.0,Wallet,Mobile App,Returned,2025-06-10,1386.0,0.0,1386.0,987.28,398.72
25297,ORD500860,2025-04-27,CUST11353,Vivaan Reddy,30.0,Chennai,Tamil Nadu,Beauty,Shampoo,4,...,20.0,Wallet,Website,Processing,2025-04-28,3036.0,607.2,2428.8,1152.06,1276.74
25298,ORD515795,2025-11-16,CUST15788,Meera Das,61.0,Delhi,Delhi,Electronics,Bluetooth Speaker,1,...,0.0,UPI,Website,Delivered,2025-11-22,3212.0,0.0,3212.0,1992.13,1219.87
25299,ORD523654,2025-03-08,CUST15898,Aditya Das,48.0,Delhi,Delhi,Fashion,Hoodie,3,...,0.0,Net Banking,Website,Delivered,2025-03-13,7410.0,0.0,7410.0,5241.04,2168.96

STEP 1 Data Profiling
--

In [152]:
df.shape

(25300, 21)

In [153]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'City',
       'State', 'Product_Category', 'Product_Name', 'Quantity', 'Unit_Price',
       'Discount_%', 'Payment_Method', 'Sales_Channel', 'Order_Status',
       'Delivery_Date', 'Gross_Sales', 'Discount_Amount', 'Net_Sales', 'Cost',
       'Profit'],
      dtype='object')

In [154]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Age                 223
City                181
State                 0
Product_Category      0
Product_Name          0
Quantity              0
Unit_Price            0
Discount_%          122
Payment_Method      166
Sales_Channel         0
Order_Status          0
Delivery_Date       133
Gross_Sales           0
Discount_Amount       0
Net_Sales             0
Cost                  0
Profit                0
dtype: int64

In [155]:
df.duplicated().sum()

np.int64(300)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25300 entries, 0 to 25299
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          25300 non-null  object
 1   Order_Date        25300 non-null  object
 2   Customer_ID       25300 non-null  object
 3   Customer_Name     25300 non-null  object
 4   Age               25077 non-null  float64
 5   City              25119 non-null  object
 6   State             25300 non-null  object
 7   Product_Category  25300 non-null  object
 8   Product_Name      25300 non-null  object
 9   Quantity          25300 non-null  int64
 10  Unit_Price        25300 non-null  float64
 11  Discount_%        25178 non-null  float64
 12  Payment_Method    25134 non-null  object
 13  Sales_Channel     25300 non-null  object
 14  Order_Status      25300 non-null  object
 15  Delivery_Date     25167 non-null  object
 16  Gross_Sales       25300 non-null  float64
 17  Discount_Amount   25300 non-null  float64
 18  Net_Sales         25300 non-null  float64
 19  Cost              25300 non-null  float64
 20  Profit            25300 non-null  float64
dtypes: float64(8), int64(1), object(12)
memory usage: 4.1+ MB

In [169]:
cat_cols = df.select_dtypes(include="object").columns
num_cols = df.select_dtypes(include="number").columns

In [158]:
df[num_cols].describe()

,Age,Quantity,Unit_Price,Discount_%,Gross_Sales,Discount_Amount,Net_Sales,Cost,Profit
count,25077.000000,25300.000000,25300.000000,25178.000000,25300.000000,25300.000000,25300.000000,25300.000000,25300.000000
mean,41.544882,3.003518,1583.673834,9.499960,4764.879249,444.783119,4320.096130,2742.951971,1577.144160
std,14.312303,1.424416,2830.752574,8.657914,9386.049402,947.231461,8764.683356,5833.506748,3142.140649
min,-5.000000,-3.000000,-100.000000,0.000000,-9804.000000,-994.500000,-8823.600000,-4840.730000,-4594.640000
25%,29.000000,2.000000,624.750000,0.000000,1473.750000,0.000000,1322.850000,814.485000,444.417500
50%,42.000000,3.000000,1139.000000,10.000000,3015.000000,166.800000,2704.500000,1682.210000,949.245000
75%,53.000000,4.000000,2041.000000,15.000000,6075.000000,541.500000,5460.000000,3448.537500,1959.745000
max,150.000000,5.000000,99999.000000,25.000000,499995.000000,49999.500000,474995.250000,300256.620000,188037.870000

In [159]:
df[cat_cols].nunique()

Order_ID            25000
Order_Date            639
Customer_ID          6802
Customer_Name         281
City                   20
State                   9
Product_Category        6
Product_Name           30
Payment_Method          6
Sales_Channel           3
Order_Status            5
Delivery_Date         371
dtype: int64

In [160]:
df["Age"].unique()

array([ 42.,  60.,  56.,  41.,  18.,  27.,  65.,  48.,  49.,  50.,  45.,
        47.,  30.,  59.,  19.,  23.,  64.,  61.,  24.,  22.,  53.,  36.,
        32.,  20.,  63.,  26.,  29.,  39.,  40.,  31.,  25.,  43.,  44.,
        57.,  34.,  62.,  51.,  52.,  55.,  58.,  38.,  54.,  46.,  37.,
        nan,  33.,  35.,  21.,  28., 120., 150.,   0.,  -5.])

In [161]:
df["Quantity"].unique()

array([ 4,  3,  1,  2,  0,  5, -3, -1])

In [162]:
df["Unit_Price"].unique()

array([4398.,  888.,  394., ..., 4421., 5462., 4000.], shape=(4685,))

In [163]:
df["Discount_%"].unique()

array([10.,  0., 25., 15., 20.,  5., nan])

In [164]:
df["Payment_Method"].unique()

array(['Net Banking', 'Debit Card', 'Wallet', 'UPI', 'Credit Card',
       'Cash on Delivery', nan], dtype=object)

In [165]:
df["Order_Status"].unique()

array(['Cancelled', 'Delivered', 'Returned', 'Processing', 'Shipped'],
      dtype=object)

STEP 2 Data Cleaning
--

In [166]:
df["Order_ID"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25295    False
25296    False
25297    False
25298    False
25299    False
Name: Order_ID, Length: 25300, dtype: bool

In [172]:
df= df.drop_duplicates()

In [173]:
cat_cols = df.select_dtypes(include="object").columns
num_cols = df.select_dtypes(include="number").columns

In [174]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [175]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Age                   0
City                180
State                 0
Product_Category      0
Product_Name          0
Quantity              0
Unit_Price            0
Discount_%          120
Payment_Method      160
Sales_Channel         0
Order_Status          0
Delivery_Date       130
Gross_Sales           0
Discount_Amount       0
Net_Sales             0
Cost                  0
Profit                0
dtype: int64

In [176]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [177]:
df["Payment_Method"] = df["Payment_Method"].fillna(df["Payment_Method"].mode()[0])

In [178]:
df["Discount_%"] = df["Discount_%"].fillna(0)

In [179]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"],format = "mixed")

In [180]:
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"],format = "mixed")

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 25299
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          25000 non-null  object
 1   Order_Date        25000 non-null  datetime64[ns]
 2   Customer_ID       25000 non-null  object
 3   Customer_Name     25000 non-null  object
 4   Age               25000 non-null  float64
 5   City              25000 non-null  object
 6   State             25000 non-null  object
 7   Product_Category  25000 non-null  object
 8   Product_Name      25000 non-null  object
 9   Quantity          25000 non-null  int64
 10  Unit_Price        25000 non-null  float64
 11  Discount_%        25000 non-null  float64
 12  Payment_Method    25000 non-null  object
 13  Sales_Channel     25000 non-null  object
 14  Order_Status      25000 non-null  object
 15  Delivery_Date     24870 non-null  datetime64[ns]
 16  Gross_Sales       25000 non-null  float64
 17  Discount_Amount   25000 non-null  float64
 18  Net_Sales         25000 non-null  float64
 19  Cost              25000 non-null  float64
 20  Profit            25000 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(10)
memory usage: 4.2+ MB

In [182]:
df["Delivery_Date"] = df["Delivery_Date"].fillna(df["Order_Date"]+pd.Timedelta(days=5))

In [183]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
City                0
State               0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_%          0
Payment_Method      0
Sales_Channel       0
Order_Status        0
Delivery_Date       0
Gross_Sales         0
Discount_Amount     0
Net_Sales           0
Cost                0
Profit              0
dtype: int64

In [184]:
df["Customer_Name"].unique()

array(['Vivaan Sharma', 'Pooja Singh', 'Aarav Kumar', 'Kabir Reddy',
       'Isha Reddy', 'Ananya Sharma', 'Meera Khan', 'Isha Gupta',
       ' Pooja Singh ', 'Rahul Patel', 'Vivaan Patel', 'Arjun Kumar',
       'Neha Khan', 'Pooja Verma', 'Priya Reddy', 'Vivaan Gupta',
       'Sneha Khan', 'Arjun Rao', 'Rohan Gupta', 'Kabir Singh',
       ' Arjun Khan ', 'Sahil Singh', 'Pooja Rao', 'Sneha Singh',
       'Rohan Reddy', 'Arjun Sharma', 'Kabir Verma', 'Neha Kumar',
       'Kabir Patel', 'Sahil Verma', 'Sneha Verma', 'Vivaan Das',
       'Arjun Reddy', 'Ananya Das', 'Aarav Gupta', 'Ananya Reddy',
       'Rohan Singh', 'Neha Singh', ' Rohan Rao ', 'Rohan Kumar',
       'Aditya Kumar', 'Aarav Patel', 'Ananya Verma', 'Meera Gupta',
       'Sahil Sharma', 'Aditya Verma', 'Sahil Patel', 'Isha Khan',
       'Neha Reddy', 'Priya Kumar', 'Meera Rao', 'Ananya Singh',
       'Ananya Kumar', 'Vivaan Khan', 'Vivaan Verma', 'Priya Rao',
       'Pooja Patel', 'Arjun Patel', 'Rohan Patel', 'Rahul Khan',
       'Arjun Khan', 'Arjun Das', 'Priya Verma', 'Vivaan Reddy',
       'Meera Verma', 'Pooja Kumar', 'Aditya Patel', 'Kabir Gupta',
       'Sneha Reddy', 'Arjun Verma', 'Aditya Das', 'Isha Singh',
       'Rahul Gupta', 'Sneha Kumar', 'Pooja Reddy', 'Sneha Gupta',
       'Aarav Das', 'Kabir Das', 'Isha Sharma', 'Rohan Verma',
       'Ananya Patel', 'Kabir Rao', 'Sahil Gupta', 'Ananya Gupta',
       'Rohan Das', 'Arjun Gupta', 'Neha Gupta', 'Sahil Kumar',
       'Aditya Singh', 'Priya Singh', 'Priya Das', 'Priya Sharma',
       'Rahul Rao', 'Rahul Singh', 'Ananya Rao', 'Sneha Rao', 'Rohan Rao',
       'Vivaan Rao', 'Ananya Khan', 'Priya Gupta', 'Rohan Khan',
       'Meera Sharma', 'Aarav Singh', 'Rahul Kumar', 'Neha Das',
       'Neha Verma', 'Aarav Khan', 'Pooja Gupta', 'Vivaan Singh',
       'Rahul Verma', 'Isha Rao', 'Aarav Rao', 'Sneha Patel', 'Sahil Das',
       'Meera Reddy', 'Rahul Sharma', 'Priya Patel', 'Meera Kumar',
       'Neha Rao', 'Rohan Sharma', 'Aditya Rao', 'Kabir Kumar',
       'Meera Patel', 'Aarav Reddy', 'Isha Kumar', ' Priya Patel ',
       'Meera Das', 'Pooja Sharma', 'Sneha Das', 'Sahil Reddy',
       ' Neha Khan ', 'Isha Das', 'Kabir Khan', 'Neha Sharma',
       'Isha Verma', 'Isha Patel', ' Arjun Singh ', 'Aditya Gupta',
       'Aarav Verma', 'Aditya Reddy', 'Pooja Das', 'Meera Singh',
       'Aditya Khan', 'Sahil Khan', 'Sahil Rao', 'Priya Khan',
       'Aditya Sharma', 'Rahul Reddy', 'Rahul Das', 'Neha Patel',
       'Sneha Sharma', ' Rohan Reddy ', 'Pooja Khan', 'Aarav Sharma',
       'Arjun Singh', 'Kabir Sharma', ' Meera Reddy ', ' Pooja Das ',
       'Vivaan Kumar', ' Isha Verma ', ' Aditya Verma ', ' Aarav Sharma ',
       ' Priya Singh ', ' Isha Das ', ' Arjun Sharma ', ' Isha Reddy ',
       ' Vivaan Rao ', ' Kabir Khan ', ' Meera Khan ', ' Kabir Verma ',
       ' Ananya Rao ', ' Rohan Singh ', ' Sneha Khan ', ' Meera Singh ',
       ' Rohan Khan ', ' Rahul Singh ', ' Pooja Patel ', ' Priya Das ',
       ' Neha Reddy ', ' Sneha Singh ', ' Sneha Gupta ', ' Vivaan Gupta ',
       ' Aditya Sharma ', ' Priya Gupta ', ' Ananya Reddy ',
       ' Aarav Verma ', ' Isha Gupta ', ' Rohan Gupta ', ' Aditya Gupta ',
       ' Arjun Verma ', ' Meera Kumar ', ' Ananya Khan ', ' Isha Kumar ',
       ' Arjun Reddy ', ' Vivaan Singh ', ' Rahul Das ', ' Isha Patel ',
       ' Meera Gupta ', ' Sahil Gupta ', ' Aarav Khan ', ' Neha Rao ',
       ' Priya Rao ', ' Priya Reddy ', ' Sneha Das ', ' Kabir Kumar ',
       ' Rahul Gupta ', ' Meera Verma ', ' Aditya Patel ', ' Sahil Das ',
       ' Neha Singh ', ' Sneha Reddy ', ' Priya Khan ', ' Isha Khan ',
       ' Pooja Rao ', ' Rahul Rao ', ' Arjun Gupta ', ' Kabir Patel ',
       ' Kabir Rao ', ' Sahil Singh ', ' Neha Sharma ', ' Ananya Gupta ',
       ' Aarav Singh ', ' Rahul Reddy ', ' Ananya Singh ',
       ' Rohan Sharma ', ' Aarav Kumar ', ' Vivaan Kumar ',
       ' Pooja Kumar ', ' Priya Sharma ', ' Priya Kumar ',
       ' Aditya Singh ', ' Rohan Verma ', ' Neha Das ', ' Arjun Das ',
       ' Meera Das ', ' Priya Verma ', ' Sneha Kumar ', ' Sahil Rao ',
       ' Aarav Gupta ', ' Sahil Verma ', ' Neha Patel ', ' Rohan Patel ',
       ' Aditya Kumar ', ' Sahil Reddy ', ' Aarav Patel ', ' Aditya Rao ',
       ' Arjun Patel ', ' Vivaan Reddy ', ' Pooja Reddy ', ' Isha Singh ',
       ' Sahil Sharma ', ' Aarav Rao ', ' Sneha Patel ', ' Vivaan Verma ',
       ' Rahul Khan ', ' Pooja Verma ', ' Rohan Kumar ', ' Meera Patel ',
       ' Kabir Singh ', ' Rahul Patel ', ' Ananya Kumar ', ' Vivaan Das ',
       ' Vivaan Sharma ', ' Kabir Das ', ' Sneha Verma ',
       ' Pooja Sharma ', ' Arjun Kumar ', ' Aditya Khan ',
       ' Meera Sharma ', ' Rahul Kumar ', ' Ananya Sharma ',
       ' Rahul Sharma ', ' Aditya Das ', ' Vivaan Khan ', ' Aarav Reddy ',
       ' Sneha Sharma ', ' Neha Verma ', ' Sahil Kumar ',
       ' Kabir Sharma ', ' Isha Rao ', ' Vivaan Patel '], dtype=object)

In [185]:
cat_cols = df.select_dtypes(include="object").columns
num_cols = df.select_dtypes(include="number").columns

In [186]:
df["Customer_Name"] = df["Customer_Name"].str.strip()

In [187]:
df["Customer_Name"].unique()

array(['Vivaan Sharma', 'Pooja Singh', 'Aarav Kumar', 'Kabir Reddy',
       'Isha Reddy', 'Ananya Sharma', 'Meera Khan', 'Isha Gupta',
       'Rahul Patel', 'Vivaan Patel', 'Arjun Kumar', 'Neha Khan',
       'Pooja Verma', 'Priya Reddy', 'Vivaan Gupta', 'Sneha Khan',
       'Arjun Rao', 'Rohan Gupta', 'Kabir Singh', 'Arjun Khan',
       'Sahil Singh', 'Pooja Rao', 'Sneha Singh', 'Rohan Reddy',
       'Arjun Sharma', 'Kabir Verma', 'Neha Kumar', 'Kabir Patel',
       'Sahil Verma', 'Sneha Verma', 'Vivaan Das', 'Arjun Reddy',
       'Ananya Das', 'Aarav Gupta', 'Ananya Reddy', 'Rohan Singh',
       'Neha Singh', 'Rohan Rao', 'Rohan Kumar', 'Aditya Kumar',
       'Aarav Patel', 'Ananya Verma', 'Meera Gupta', 'Sahil Sharma',
       'Aditya Verma', 'Sahil Patel', 'Isha Khan', 'Neha Reddy',
       'Priya Kumar', 'Meera Rao', 'Ananya Singh', 'Ananya Kumar',
       'Vivaan Khan', 'Vivaan Verma', 'Priya Rao', 'Pooja Patel',
       'Arjun Patel', 'Rohan Patel', 'Rahul Khan', 'Arjun Das',
       'Priya Verma', 'Vivaan Reddy', 'Meera Verma', 'Pooja Kumar',
       'Aditya Patel', 'Kabir Gupta', 'Sneha Reddy', 'Arjun Verma',
       'Aditya Das', 'Isha Singh', 'Rahul Gupta', 'Sneha Kumar',
       'Pooja Reddy', 'Sneha Gupta', 'Aarav Das', 'Kabir Das',
       'Isha Sharma', 'Rohan Verma', 'Ananya Patel', 'Kabir Rao',
       'Sahil Gupta', 'Ananya Gupta', 'Rohan Das', 'Arjun Gupta',
       'Neha Gupta', 'Sahil Kumar', 'Aditya Singh', 'Priya Singh',
       'Priya Das', 'Priya Sharma', 'Rahul Rao', 'Rahul Singh',
       'Ananya Rao', 'Sneha Rao', 'Vivaan Rao', 'Ananya Khan',
       'Priya Gupta', 'Rohan Khan', 'Meera Sharma', 'Aarav Singh',
       'Rahul Kumar', 'Neha Das', 'Neha Verma', 'Aarav Khan',
       'Pooja Gupta', 'Vivaan Singh', 'Rahul Verma', 'Isha Rao',
       'Aarav Rao', 'Sneha Patel', 'Sahil Das', 'Meera Reddy',
       'Rahul Sharma', 'Priya Patel', 'Meera Kumar', 'Neha Rao',
       'Rohan Sharma', 'Aditya Rao', 'Kabir Kumar', 'Meera Patel',
       'Aarav Reddy', 'Isha Kumar', 'Meera Das', 'Pooja Sharma',
       'Sneha Das', 'Sahil Reddy', 'Isha Das', 'Kabir Khan',
       'Neha Sharma', 'Isha Verma', 'Isha Patel', 'Arjun Singh',
       'Aditya Gupta', 'Aarav Verma', 'Aditya Reddy', 'Pooja Das',
       'Meera Singh', 'Aditya Khan', 'Sahil Khan', 'Sahil Rao',
       'Priya Khan', 'Aditya Sharma', 'Rahul Reddy', 'Rahul Das',
       'Neha Patel', 'Sneha Sharma', 'Pooja Khan', 'Aarav Sharma',
       'Kabir Sharma', 'Vivaan Kumar'], dtype=object)

In [188]:
df["Customer_Name"].str.capitalize()

0        Vivaan sharma
1          Pooja singh
2          Aarav kumar
3          Kabir reddy
4           Isha reddy
             ...
25295      Rahul patel
25296      Rahul singh
25297     Vivaan reddy
25298        Meera das
25299       Aditya das
Name: Customer_Name, Length: 25000, dtype: object

In [225]:
df[cat_cols] = df[cat_cols].apply(lambda x : x.str.title())
df[cat_cols] = df[cat_cols].apply(lambda x : x.str.strip())

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 25299
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          25000 non-null  object
 1   Order_Date        25000 non-null  datetime64[ns]
 2   Customer_ID       25000 non-null  object
 3   Customer_Name     25000 non-null  object
 4   Age               25000 non-null  float64
 5   City              25000 non-null  object
 6   State             25000 non-null  object
 7   Product_Category  25000 non-null  object
 8   Product_Name      25000 non-null  object
 9   Quantity          25000 non-null  int64
 10  Unit_Price        25000 non-null  float64
 11  Discount_%        25000 non-null  float64
 12  Payment_Method    25000 non-null  object
 13  Sales_Channel     25000 non-null  object
 14  Order_Status      25000 non-null  object
 15  Delivery_Date     25000 non-null  datetime64[ns]
 16  Gross_Sales       25000 non-null  float64
 17  Discount_Amount   25000 non-null  float64
 18  Net_Sales         25000 non-null  float64
 19  Cost              25000 non-null  float64
 20  Profit            25000 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(10)
memory usage: 4.2+ MB

In [191]:
df.loc[(df["Age"] < 10) | (df["Age"] > 80), "Age"] = np.nan

df["Age"] = df["Age"].fillna(df["Age"].median())

In [192]:
df["Age"].min()

18.0

In [193]:
df["Age"].max()

65.0

In [194]:
df["Age"].unique()

array([42.        , 60.        , 56.        , 41.        , 18.        ,
       27.        , 65.        , 48.        , 49.        , 50.        ,
       45.        , 47.        , 30.        , 59.        , 19.        ,
       23.        , 64.        , 61.        , 24.        , 22.        ,
       53.        , 36.        , 32.        , 20.        , 63.        ,
       26.        , 29.        , 39.        , 40.        , 31.        ,
       25.        , 43.        , 44.        , 57.        , 34.        ,
       62.        , 51.        , 52.        , 55.        , 58.        ,
       38.        , 54.        , 46.        , 37.        , 41.54987893,
       33.        , 35.        , 21.        , 28.        ])

In [195]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
City                0
State               0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_%          0
Payment_Method      0
Sales_Channel       0
Order_Status        0
Delivery_Date       0
Gross_Sales         0
Discount_Amount     0
Net_Sales           0
Cost                0
Profit              0
dtype: int64

In [196]:

df[df["Quantity"]<=0]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,City,State,Product_Category,Product_Name,Quantity,...,Discount_%,Payment_Method,Sales_Channel,Order_Status,Delivery_Date,Gross_Sales,Discount_Amount,Net_Sales,Cost,Profit
19,Ord519435,2025-10-02,Cust13046,Arjun Rao,64.000000,Ahmedabad,Gujarat,Beauty,Face Wash,0,...,0.0,Credit Card,Marketplace,Returned,2025-10-07,0.0,0.00,0.00,0.00,0.00
1986,Ord503286,2025-10-11,Cust10409,Aarav Kumar,60.000000,Ahmedabad,Gujarat,Electronics,Bluetooth Speaker,-3,...,10.0,Upi,Marketplace,Delivered,2025-10-17,-9804.0,-980.40,-8823.60,-4228.96,-4594.64
2418,Ord502361,2025-04-04,Cust16559,Neha Das,57.000000,Mumbai,Maharashtra,Grocery,Cooking Oil,-3,...,5.0,Upi,Marketplace,Processing,2025-04-09,-1923.0,-96.15,-1826.85,-1298.68,-528.17
2564,Ord512033,2025-01-07,Cust13372,Kabir Sharma,24.000000,Mumbai,Maharashtra,Home & Kitchen,Electric Kettle,-3,...,10.0,Net Banking,Website,Delivered,2025-01-14,-4725.0,-472.50,-4252.50,-2553.39,-1699.11
2862,Ord507330,2025-07-13,Cust10235,Aditya Rao,39.000000,Bangalore,Karnataka,Grocery,Cooking Oil,-3,...,20.0,Upi,Marketplace,Returned,2025-07-20,-1218.0,-243.60,-974.40,-696.71,-277.69
3358,Ord513241,2025-05-21,Cust11076,Rahul Patel,57.000000,Hyderabad,Telangana,Fashion,Hoodie,-3,...,5.0,Credit Card,Mobile App,Processing,2025-05-23,-6729.0,-336.45,-6392.55,-4840.73,-1551.82
3957,Ord517401,2025-01-04,Cust12875,Isha Kumar,37.000000,Vijayawada,Andhra Pradesh,Grocery,Coffee,0,...,20.0,Cash On Delivery,Website,Shipped,2025-01-09,0.0,0.00,0.00,0.00,0.00
4181,Ord515017,2025-05-23,Cust13397,Pooja Sharma,43.000000,Mumbai,Maharashtra,Grocery,Coffee,-1,...,0.0,Net Banking,Mobile App,Delivered,2025-05-29,-843.0,-0.00,-843.00,-670.61,-172.39
4194,Ord511307,2025-10-02,Cust14025,Ananya Khan,21.000000,Vijayawada,Andhra Pradesh,Sports,Cricket Bat,0,...,5.0,Cash On Delivery,Website,Processing,2025-10-08,0.0,0.00,0.00,0.00,0.00
4966,Ord500410,2025-10-16,Cust16698,Kabir Kumar,35.000000,Bangalore,Karnataka,Grocery,Rice 5Kg,-1,...,25.0,Upi,Website,Cancelled,2025-10-21,-439.0,-109.75,-329.25,-160.77,-168.48
5126,Ord519474,2025-12-26,Cust10207,Rahul Kumar,58.000000,Vijayawada,Andhra Pradesh,Fashion,Jeans,-3,...,0.0,Credit Card,Mobile App,Delivered,2026-01-01,-4857.0,-0.00,-4857.00,-2925.65,-1931.35
5681,Ord508918,2025-04-24,Cust15049,Meera Kumar,64.000000,Kolkata,West Bengal,Grocery,Dry Fruits,-1,...,0.0,Wallet,Mobile App,Returned,2025-04-25,-394.0,-0.00,-394.00,-217.47,-176.53
6244,Ord502640,2025-11-30,Cust10722,Meera Singh,40.000000,Pune,Maharashtra,Beauty,Moisturizer,-1,...,0.0,Debit Card,Mobile App,Returned,2025-12-01,-787.0,-0.00,-787.00,-620.92,-166.08
7156,Ord523587,2025-06-29,Cust11197,Priya Reddy,42.000000,Kolkata,West Bengal,Beauty,Sunscreen,-3,...,15.0,Wallet,Mobile App,Delivered,2025-07-01,-1620.0,-243.00,-1377.00,-1126.61,-250.39
7520,Ord515532,2025-08-17,Cust16816,Rohan Kumar,50.000000,Jaipur,Rajasthan,Grocery,Dry Fruits,-3,...,0.0,Wallet,Marketplace,Delivered,2025-08-20,-981.0,-0.00,-981.00,-520.28,-460.72
7857,Ord504045,2025-02-03,Cust10190,Rohan Reddy,50.000000,Vijayawada,Andhra Pradesh,Sports,Football,0,...,5.0,Wallet,Website,Processing,2025-02-08,0.0,0.00,0.00,0.00,0.00
8604,Ord517305,2025-04-22,Cust15659,Aditya Kumar,51.000000,Jaipur,Rajasthan,Beauty,Sunscreen,-3,...,0.0,Credit Card,Marketplace,Delivered,2025-04-23,-1857.0,-0.00,-1857.00,-946.08,-910.92
9557,Ord509861,2025-04-26,Cust12654,Rohan Khan,51.000000,Pune,Maharashtra,Electronics,Keyboard,0,...,5.0,Net Banking,Website,Returned,2025-04-27,0.0,0.00,0.00,0.00,0.00
11319,Ord501844,2025-05-25,Cust12208,Kabir Singh,52.000000,Bangalore,Karnataka,Sports,Yoga Mat,-1,...,0.0,Upi,Mobile App,Cancelled,2025-05-31,-1039.0,-0.00,-1039.00,-668.78,-370.22
11858,Ord517012,2025-06-21,Cust16548,Aarav Gupta,34.000000,Jaipur,Rajasthan,Sports,Dumbbells,-3,...,0.0,Upi,Marketplace,Shipped,2025-06-26,-5940.0,-0.00,-5940.00,-4379.37,-1560.63
12484,Ord517024,2025-07-25,Cust15875,Vivaan Kumar,18.000000,Pune,Maharashtra,Fashion,Jeans,0,...,10.0,Credit Card,Mobile App,Shipped,2025-08-01,0.0,0.00,0.00,0.00,0.00
12543,Ord507956,2025-11-22,Cust13025,Aditya Patel,55.000000,Bangalore,Karnataka,Grocery,Rice 5Kg,-3,...,0.0,Wallet,Mobile App,Delivered,2025-11-25,-1110.0,-0.00,-1110.00,-768.77,-341.23
13123,Ord521724,2025-05-31,Cust11470,Isha Kumar,57.000000,Chennai,Tamil Nadu,Sports,Football,0,...,5.0,Wallet,Marketplace,Delivered,2025-06-01,0.0,0.00,0.00,0.00,0.00
13314,Ord523602,2025-12-03,Cust10154,Rahul Gupta,28.000000,Bangalore,Karnataka,Grocery,Biscuits,-3,...,10.0,Debit Card,Website,Delivered,2025-12-05,-498.0,-49.80,-448.20,-272.78,-175.42
14082,Ord504187,2025-05-30,Cust12012,Neha Reddy,41.549879,Bangalore,Karnataka,Grocery,Biscuits,0,...,0.0,Upi,Mobile App,Delivered,2025-06-06,0.0,0.00,0.00,0.00,0.00
15894,Ord501193,2025-02-20,Cust11607,Rohan Rao,51.000000,Pune,Maharashtra,Home & Kitchen,Electric Kettle,-1,...,10.0,Net Banking,Website,Cancelled,2025-02-21,-1717.0,-171.70,-1545.30,-1221.49,-323.81
16593,Ord506668,2025-12-02,Cust14227,Ananya Verma,56.000000,Delhi,Delhi,Sports,Cricket Bat,-1,...,5.0,Upi,Mobile App,Shipped,2025-12-08,-4335.0,-216.75,-4118.25,-2897.08,-1221.17
17276,Ord505609,2025-05-16,Cust14996,Rahul Reddy,23.000000,Pune,Maharashtra,Grocery,Rice 5Kg,-3,...,5.0,Upi,Website,Delivered,2025-05-22,-1539.0,-76.95,-1462.05,-705.39,-756.66
17647,Ord501946,2025-06-12,Cust11877,Meera Reddy,20.000000,Hyderabad,Telangana,Beauty,Moisturizer,-3,...,0.0,Cash On Delivery,Website,Processing,2025-06-19,-3345.0,-0.00,-3345.00,-1799.67,-1545.33
17849,Ord512191,2025-10-28,Cust16725,Rahul Singh,58.000000,Kolkata,West Bengal,Sports,Yoga Mat,0,...,10.0,Credit Card,Mobile App,Delivered,2025-11-04,0.0,0.00,0.00,0.00,0.00
18834,Ord514380,2025-03-14,Cust15226,Sneha Singh,48.000000,Bangalore,Karnataka,Sports,Running Bottle,-1,...,10.0,Wallet,Marketplace,Processing,2025-03-18,-469.0,-46.90,-422.10,-261.85,-160.25
19686,Ord513648,2025-09-10,Cust12202,Rohan Rao,27.000000,Kolkata,West Bengal,Electronics,Keyboard,-1,...,0.0,Credit Card,Mobile App,Returned,2025-09-11,-2328.0,-0.00,-2328.00,-1565.45,-762.55
19803,Ord512450,2025-03-04,Cust11410,Vivaan Khan,38.000000,Pune,Maharashtra,Home & Kitchen,Electric Kettle,0,...,15.0,Cash On Delivery,Mobile App,Delivered,2025-03-06,0.0,0.00,0.00,0.00,0.00
20372,Ord507124,2025-05-02,Cust14929,Rahul Khan,36.000000,Hyderabad,Telangana,Grocery,Dry Fruits,-3,...,5.0,Wallet,Mobile App,Returned,2025-05-03,-3954.0,-197.70,-3756.30,-2639.01,-1117.29
21786,Ord520114,2025-07-16,Cust12052,Aditya Sharma,41.000000,Mumbai,Maharashtra,Fashion,Sneakers,-1,...,25.0,Wallet,Mobile App,Delivered,2025-07-17,-3978.0,-994.50,-2983.50,-1642.25,-1341.25
22089,Ord513319,2025-09-15,Cust16168,Sneha Singh,63.000000,Pune,Maharashtra,Fashion,Backpack,-3,...,0.0,Upi,Website,Delivered,2025-09-18,-2907.0,-0.00,-2907.00,-1921.26,-985.74
22124,Ord511240,2025-09-17,Cust16714,Vivaan Verma,41.000000,Vijayawada,Andhra Pradesh,Home & Kitchen,Electric Kettle,-1,...,20.0,Net Banking,Website,Delivered,2025-09-22,-1397.0,-279.40,-1117.60,-539.66,-577.94
23378,Ord523116,2025-10-02,Cust10295,Pooja Das,34.000000,Bangalore,Karnataka,Home & Kitchen,Electric Kettle,-1,...,0.0,Cash On Delivery,Mobile App,Delivered,2025-10-04,-1291.0,-0.00,-1291.00,-1040.48,-250.52
23441,Ord503380,2025-05-02,Cust10189,Sneha Khan,61.000000,Mumbai,Maharashtra,Home & Kitchen,Cookware Set,-3,...,15.0,Net Banking,Marketplace,Delivered,2025-05-03,-5202.0,-780.30,-4421.70,-3560.46,-861.24
23787,Ord523393,2025-08-23,Cust16701,Isha Reddy,39.000000,Jaipur,Rajasthan,Electronics,Wireless Headphones,-1,...,0.0,Wallet,Website,Cancelled,2025-08-28,-2237.0,-0.00,-2237.00,-1241.47,-995.53

In [197]:
df = df.drop(df[df["Quantity"]<=0].index)

In [198]:
df[df["Quantity"]<=0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, City, State, Product_Category, Product_Name, Quantity, Unit_Price, Discount_%, Payment_Method, Sales_Channel, Order_Status, Delivery_Date, Gross_Sales, Discount_Amount, Net_Sales, Cost, Profit]
Index: []

[0 rows x 21 columns]

In [199]:
df = df.drop(df[df["Unit_Price"]<=0].index)

In [200]:
df[df["Unit_Price"]<=0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, City, State, Product_Category, Product_Name, Quantity, Unit_Price, Discount_%, Payment_Method, Sales_Channel, Order_Status, Delivery_Date, Gross_Sales, Discount_Amount, Net_Sales, Cost, Profit]
Index: []

[0 rows x 21 columns]

In [201]:
df[df["Quantity"]*df["Unit_Price"] != df["Gross_Sales"]]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, City, State, Product_Category, Product_Name, Quantity, Unit_Price, Discount_%, Payment_Method, Sales_Channel, Order_Status, Delivery_Date, Gross_Sales, Discount_Amount, Net_Sales, Cost, Profit]
Index: []

[0 rows x 21 columns]

In [202]:
df[df["Gross_Sales"]-df["Discount_Amount"] != df["Net_Sales"]]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Age, City, State, Product_Category, Product_Name, Quantity, Unit_Price, Discount_%, Payment_Method, Sales_Channel, Order_Status, Delivery_Date, Gross_Sales, Discount_Amount, Net_Sales, Cost, Profit]
Index: []

[0 rows x 21 columns]

STEP 3 Data Validation
--

In [203]:
df.shape

(24941, 21)

In [204]:
df["Delivery_Days"] = df["Delivery_Date"] - df["Order_Date"]

In [205]:
df["Delivery_Days"].unique()

<TimedeltaArray>
[   '6 days',    '7 days',    '4 days',    '3 days',    '1 days',    '2 days',
    '5 days', '-116 days',   '95 days',   '61 days',  '-56 days',  '267 days',
  '-84 days',  '151 days',  '-53 days',  '-24 days',  '-27 days',  '185 days',
  '-57 days',  '146 days', '-204 days',  '-23 days', '-230 days', '-145 days',
  '-87 days', '-203 days', '-234 days',   '33 days',   '94 days', '-168 days',
   '66 days', '-231 days', '-139 days', '-229 days',   '92 days',  '324 days',
 '-318 days',   '30 days',  '207 days',  '181 days', '-142 days',   '32 days',
  '-28 days', '-114 days', '-169 days', '-322 days',  '-54 days',  '120 days',
  '-26 days',  '183 days',   '37 days',  '121 days', '-262 days', '-172 days',
 '-141 days',   '91 days',   '36 days', '-202 days', '-170 days',   '35 days']
Length: 60, dtype: timedelta64[ns]

In [206]:
df["Delivery_Days"] = df["Delivery_Days"].dt.days

In [207]:
df["Delivery_Days"].unique()

array([   6,    7,    4,    3,    1,    2,    5, -116,   95,   61,  -56,
        267,  -84,  151,  -53,  -24,  -27,  185,  -57,  146, -204,  -23,
       -230, -145,  -87, -203, -234,   33,   94, -168,   66, -231, -139,
       -229,   92,  324, -318,   30,  207,  181, -142,   32,  -28, -114,
       -169, -322,  -54,  120,  -26,  183,   37,  121, -262, -172, -141,
         91,   36, -202, -170,   35])

In [208]:
df["Delivery_Days"] = df["Delivery_Days"].astype("int64")

In [209]:
df["Delivery_Days"].dtype

dtype('int64')

In [210]:
df.loc[(df["Delivery_Days"] <=0) | (df["Delivery_Days"] >=30),"Delivery_Days"] = np.nan

In [211]:
df["Delivery_Days"].unique()

array([ 6.,  7.,  4.,  3.,  1.,  2.,  5., nan])

In [212]:
df["Delivery_Days"] = df["Delivery_Days"].fillna(df["Delivery_Days"].median())

In [213]:
df["Delivery_Days"].unique()

array([6., 7., 4., 3., 1., 2., 5.])

In [214]:
df["Customer_ID"].nunique()

6799

In [215]:
un_df = df.drop_duplicates(subset="Customer_ID")
un_df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,City,State,Product_Category,Product_Name,Quantity,...,Payment_Method,Sales_Channel,Order_Status,Delivery_Date,Gross_Sales,Discount_Amount,Net_Sales,Cost,Profit,Delivery_Days
0,Ord521129,2025-02-12,Cust15482,Vivaan Sharma,42.0,Bangalore,Karnataka,Electronics,Smart Watch,4,...,Net Banking,Marketplace,Cancelled,2025-02-18,17592.0,1759.20,15832.80,9794.82,6037.98,6.0
1,Ord501246,2025-06-04,Cust10010,Pooja Singh,60.0,Ahmedabad,Gujarat,Fashion,Jeans,3,...,Debit Card,Website,Delivered,2025-06-10,2664.0,0.00,2664.00,1474.13,1189.87,6.0
2,Ord507827,2025-05-07,Cust13534,Aarav Kumar,56.0,Mumbai,Maharashtra,Beauty,Face Wash,3,...,Wallet,Marketplace,Delivered,2025-05-14,1182.0,295.50,886.50,471.03,415.47,7.0
3,Ord501610,2025-12-25,Cust15446,Kabir Reddy,41.0,Bangalore,Karnataka,Grocery,Coffee,1,...,Wallet,Mobile App,Cancelled,2025-12-31,534.0,80.10,453.90,333.30,120.60,6.0
4,Ord504043,2025-02-01,Cust16760,Isha Reddy,18.0,Pune,Maharashtra,Electronics,Usb-C Hub,4,...,Net Banking,Marketplace,Returned,2025-02-05,8128.0,1625.60,6502.40,3459.20,3043.20,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25139,Ord518141,2025-10-31,Cust12070,Isha Gupta,18.0,Mumbai,Maharashtra,Home & Kitchen,Bedsheet,1,...,Cash On Delivery,Website,Delivered,2025-11-07,675.0,168.75,506.25,333.88,172.37,7.0
25188,Ord522002,2025-10-12,Cust15301,Sneha Gupta,20.0,Kolkata,West Bengal,Fashion,Backpack,2,...,Upi,Marketplace,Returned,2025-10-18,4368.0,436.80,3931.20,1946.28,1984.92,6.0
25230,Ord501021,2025-03-12,Cust15343,Priya Das,28.0,Mumbai,Maharashtra,Fashion,T-Shirt,5,...,Net Banking,Website,Processing,2025-03-18,5455.0,1091.00,4364.00,2405.44,1958.56,6.0
25238,Ord512206,2025-04-27,Cust12044,Rahul Rao,30.0,Delhi,Delhi,Beauty,Face Wash,5,...,Net Banking,Website,Processing,2025-05-03,2480.0,248.00,2232.00,1551.48,680.52,6.0
25297,Ord500860,2025-04-27,Cust11353,Vivaan Reddy,30.0,Chennai,Tamil Nadu,Beauty,Shampoo,4,...,Wallet,Website,Processing,2025-04-28,3036.0,607.20,2428.80,1152.06,1276.74,1.0

In [216]:
cust =df.groupby(["Customer_ID","Customer_Name"]).agg(Total_Orders =("Order_ID","count"))
cust

                           Total_Orders
Customer_ID Customer_Name
Cust10001   Vivaan Khan               7
Cust10002   Priya Singh               3
Cust10003   Sahil Das                 4
Cust10004   Vivaan Verma              7
Cust10005   Arjun Sharma              4
...                                 ...
Cust16995   Sneha Khan                5
Cust16997   Isha Khan                 5
Cust16998   Kabir Patel               5
Cust16999   Isha Das                  1
Cust17000   Kabir Khan                9

[6799 rows x 1 columns]

In [217]:
cust.sort_values("Total_Orders", ascending=False)

                           Total_Orders
Customer_ID Customer_Name
Cust11688   Ananya Gupta             13
Cust12965   Vivaan Reddy             13
Cust13780   Vivaan Rao               13
Cust15067   Meera Verma              12
Cust13524   Neha Patel               11
...                                 ...
Cust12975   Meera Gupta               1
Cust12967   Rohan Patel               1
Cust16103   Neha Das                  1
Cust12956   Aditya Patel              1
Cust13496   Neha Das                  1

[6799 rows x 1 columns]

In [218]:
orde = np.sum(df["Net_Sales"])/(df["Order_ID"].count())
orde

np.float64(4322.445798083477)

In [219]:
df.groupby(["Customer_ID","Customer_Name"]).agg(
    Total_amount = ("Net_Sales","sum"),
    Avg_Order_val = ("Net_Sales","mean")   
)

                           Total_amount  Avg_Order_val
Customer_ID Customer_Name
Cust10001   Vivaan Khan        20435.35    2919.335714
Cust10002   Priya Singh         6287.80    2095.933333
Cust10003   Sahil Das           6611.50    1652.875000
Cust10004   Vivaan Verma       27641.60    3948.800000
Cust10005   Arjun Sharma       15387.30    3846.825000
...                                 ...            ...
Cust16995   Sneha Khan         46420.50    9284.100000
Cust16997   Isha Khan          28502.90    5700.580000
Cust16998   Kabir Patel         9453.25    1890.650000
Cust16999   Isha Das            1956.60    1956.600000
Cust17000   Kabir Khan         22665.30    2518.366667

[6799 rows x 2 columns]

step 3B Feature Engineering
--

In [229]:
df["year"] = df["Order_Date"].dt.year
df["Month_Name"] = df["Order_Date"].dt.month_name()
df["Month_Num"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day
df["Quater"] = df["Order_Date"].dt.quarter
df["Week"] = df["Order_Date"].dt.weekday

In [221]:
df["Profit_Margin_%"] = df["Profit"]/df["Net_Sales"]*100

In [222]:
df["Quantity"].sum()

np.int64(75135)

In [227]:
sales_metrics = df[["Order_ID","Customer_ID","Quantity","Cost","Unit_Price","Discount_%"]]
sales_metrics

        Order_ID Customer_ID  Quantity     Cost  Unit_Price  Discount_%
0      Ord521129   Cust15482         4  9794.82      4398.0        10.0
1      Ord501246   Cust10010         3  1474.13       888.0         0.0
2      Ord507827   Cust13534         3   471.03       394.0        25.0
3      Ord501610   Cust15446         1   333.30       534.0        15.0
4      Ord504043   Cust16760         4  3459.20      2032.0        20.0
...          ...         ...       ...      ...         ...         ...
25295  Ord521575   Cust12470         3  2718.69      1415.0        20.0
25296  Ord505390   Cust11490         3   987.28       462.0         0.0
25297  Ord500860   Cust11353         4  1152.06       759.0        20.0
25298  Ord515795   Cust15788         1  1992.13      3212.0         0.0
25299  Ord523654   Cust15898         3  5241.04      2470.0         0.0

[24941 rows x 6 columns]

In [231]:
sales_metrics["Gross_Sales"] = sales_metrics["Quantity"]*sales_metrics["Unit_Price"]
sales_metrics["Discount_Amount"] = sales_metrics["Gross_Sales"]*sales_metrics["Discount_%"]/100
sales_metrics["Net_Sales"] = sales_metrics["Gross_Sales"]-sales_metrics["Discount_Amount"]
sales_metrics["Profit"] = sales_metrics["Net_Sales"]-sales_metrics["Cost"]
sales_metrics["Profit_Margin"] = sales_metrics["Profit"]/sales_metrics["Net_Sales"]*100

C:\Users\faree\AppData\Local\Temp\ipykernel_16040\860506067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_metrics["Gross_Sales"] = sales_metrics["Quantity"]*sales_metrics["Unit_Price"]
C:\Users\faree\AppData\Local\Temp\ipykernel_16040\860506067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_metrics["Discount_Amount"] = sales_metrics["Gross_Sales"]*sales_metrics["Discount_%"]/100
C:\Users\faree\AppData\Local\Temp\ipykernel_16040\860506067.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_metrics["Net_Sales"] = sales_metrics["Gross_Sales"]-sales_metrics["Discount_Amount"]
C:\Users\faree\AppData\Local\Temp\ipykernel_16040\860506067.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_metrics["Profit"] = sales_metrics["Net_Sales"]-sales_metrics["Cost"]
C:\Users\faree\AppData\Local\Temp\ipykernel_16040\860506067.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_metrics["Profit_Margin"] = sales_metrics["Profit"]/sales_metrics["Net_Sales"]*100

In [232]:
sales_metrics

,Order_ID,Customer_ID,Quantity,Cost,Unit_Price,Discount_%,Gross_Sales,Discount_Amount,Net_Sales,Profit,Profit_Margin
0,Ord521129,Cust15482,4,9794.82,4398.0,10.0,17592.0,1759.2,15832.8,6037.98,38.135895
1,Ord501246,Cust10010,3,1474.13,888.0,0.0,2664.0,0.0,2664.0,1189.87,44.664790
2,Ord507827,Cust13534,3,471.03,394.0,25.0,1182.0,295.5,886.5,415.47,46.866328
3,Ord501610,Cust15446,1,333.30,534.0,15.0,534.0,80.1,453.9,120.60,26.569729
4,Ord504043,Cust16760,4,3459.20,2032.0,20.0,8128.0,1625.6,6502.4,3043.20,46.801181
...,...,...,...,...,...,...,...,...,...,...,...
25295,Ord521575,Cust12470,3,2718.69,1415.0,20.0,4245.0,849.0,3396.0,677.31,19.944346
25296,Ord505390,Cust11490,3,987.28,462.0,0.0,1386.0,0.0,1386.0,398.72,28.767677
25297,Ord500860,Cust11353,4,1152.06,759.0,20.0,3036.0,607.2,2428.8,1276.74,52.566700
25298,Ord515795,Cust15788,1,1992.13,3212.0,0.0,3212.0,0.0,3212.0,1219.87,37.978518
25299,Ord523654,Cust15898,3,5241.04,2470.0,0.0,7410.0,0.0,7410.0,2168.96,29.270715

In [233]:
cust_metrics = df.groupby(["Customer_ID","Customer_Name"]).agg(
        Total_rders = ("Order_ID","count"),
        Total_Sales = ("Net_Sales","sum"),
        Avg_ord_val = ("Net_Sales","mean")
)
cust_metrics

                           Total_rders  Total_Sales  Avg_ord_val
Customer_ID Customer_Name
Cust10001   Vivaan Khan              7     20435.35  2919.335714
Cust10002   Priya Singh              3      6287.80  2095.933333
Cust10003   Sahil Das                4      6611.50  1652.875000
Cust10004   Vivaan Verma             7     27641.60  3948.800000
Cust10005   Arjun Sharma             4     15387.30  3846.825000
...                                ...          ...          ...
Cust16995   Sneha Khan               5     46420.50  9284.100000
Cust16997   Isha Khan                5     28502.90  5700.580000
Cust16998   Kabir Patel              5      9453.25  1890.650000
Cust16999   Isha Das                 1      1956.60  1956.600000
Cust17000   Kabir Khan               9     22665.30  2518.366667

[6799 rows x 3 columns]

In [234]:
df["delivery_perfomance"] = df["Delivery_Days"].apply(lambda x :
                                                      "Fast" if(x>=1 and x<=3)
                                                      else "Normal" if(x>=4 and x<=6)
                                                     else "Slow")

In [237]:
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,City,State,Product_Category,Product_Name,Quantity,...,Profit,Delivery_Days,year,Month_Name,Month_Num,Day,Quater,Week,Profit_Margin_%,delivery_perfomance
0,Ord521129,2025-02-12,Cust15482,Vivaan Sharma,42.0,Bangalore,Karnataka,Electronics,Smart Watch,4,...,6037.98,6.0,2025,February,2,12,1,2,38.135895,Normal
1,Ord501246,2025-06-04,Cust10010,Pooja Singh,60.0,Ahmedabad,Gujarat,Fashion,Jeans,3,...,1189.87,6.0,2025,June,6,4,2,2,44.664790,Normal
2,Ord507827,2025-05-07,Cust13534,Aarav Kumar,56.0,Mumbai,Maharashtra,Beauty,Face Wash,3,...,415.47,7.0,2025,May,5,7,2,2,46.866328,Slow
3,Ord501610,2025-12-25,Cust15446,Kabir Reddy,41.0,Bangalore,Karnataka,Grocery,Coffee,1,...,120.60,6.0,2025,December,12,25,4,3,26.569729,Normal
4,Ord504043,2025-02-01,Cust16760,Isha Reddy,18.0,Pune,Maharashtra,Electronics,Usb-C Hub,4,...,3043.20,4.0,2025,February,2,1,1,5,46.801181,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25295,Ord521575,2025-05-24,Cust12470,Rahul Patel,60.0,Chennai,Tamil Nadu,Home & Kitchen,Bedsheet,3,...,677.31,6.0,2025,May,5,24,2,5,19.944346,Normal
25296,Ord505390,2025-06-03,Cust11490,Rahul Singh,55.0,Pune,Maharashtra,Beauty,Sunscreen,3,...,398.72,7.0,2025,June,6,3,2,1,28.767677,Slow
25297,Ord500860,2025-04-27,Cust11353,Vivaan Reddy,30.0,Chennai,Tamil Nadu,Beauty,Shampoo,4,...,1276.74,1.0,2025,April,4,27,2,6,52.566700,Fast
25298,Ord515795,2025-11-16,Cust15788,Meera Das,61.0,Delhi,Delhi,Electronics,Bluetooth Speaker,1,...,1219.87,6.0,2025,November,11,16,4,6,37.978518,Normal
25299,Ord523654,2025-03-08,Cust15898,Aditya Das,48.0,Delhi,Delhi,Fashion,Hoodie,3,...,2168.96,5.0,2025,March,3,8,1,5,29.270715,Normal

In [238]:
df.to_csv("E-Commerce_cleaned.csv",index=False)